#
# Watchtower - Cloud Monitoring Service
#
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    hostname: watchtower
    domainname: ${MYDOMAIN}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - Gooby
