#
# EmbyStat - Reports on Emby stats
#
  embystat:
    image: linuxserver/embystat
    container_name: embystat
    hostname: embystat
    domainname: ${MYDOMAIN}
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_healthy
    environment:
      - PUID=${USERID}
      - PGID=${GROUPID}
      - TZ=${TIMEZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.backend=embystat"
      - "traefik.frontend.rule=Host:embystat.${MYDOMAIN}"
      - "traefik.port=6555"
      - "traefik.docker.network=omninet"
      #- "traefik.frontend.headers.SSLHost=${MYDOMAIN}"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=${MYDOMAIN}"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /bin/netstat:/bin/netstat:ro
      - ${CONFIGS}/EmbyStat:/config
    networks:
      - Gooby
    cpu_shares: 1024
    healthcheck:
      test: ["CMD-SHELL", "netstat -ntlp | grep :6555"]
      interval: 10s
      timeout: 2s
      retries: 3
